# Generated by Django 4.1.4 on 2022-12-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', 'surname'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
    ]
